### PR TITLE
replaced "create_function" with anonymous functions

### PR DESCRIPTION
**Pull request by jens-t**
for compatibility with php 7.2, min. php version is now 5.3.0

### CODE REVIEW

**Comment by jens-t** [comment]
@electrolinux can you please look into this pull request, thanks!

**Comment by electrolinux** [comment]
Hello @jens-t 

thanks for this PR.
I'm no longer using this repo, but it seems to be the most used of the phpquery forks (because of it's packagist link) and I would try not to break anything...
So what would be the minimal PHP version to use after merging your PR?
And can you update the composer.json accordingly?

I suppose I'll do a new "Release", maybe a 1.0-rc1 or something

**Comment by jens-t** [comment]
> So what would be the minimal PHP version to use after merging your PR?
The minimum version for anonymous functions would be 5.3.0.

> And can you update the composer.json accordingly?
You mean i should set the version property to `1.0-rc1`? I add a commit for this ...

**Comment by jens-t** [comment]
thanks!

**Pull request merged**
